/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_ctx {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_stream {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_buffer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_fraction {
    pub num: u32,
    pub den: u32,
}
pub type funnel_buffer_callback = ::std::option::Option<
    unsafe extern "C" fn(
        opaque: *mut ::std::os::raw::c_void,
        stream: *mut funnel_stream,
        buf: *mut funnel_buffer,
    ),
>;
#[repr(u32)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum funnel_mode {
    FUNNEL_ASYNC = 0,
    FUNNEL_DOUBLE_BUFFERED = 1,
    FUNNEL_SINGLE_BUFFERED = 2,
    FUNNEL_SYNCHRONOUS = 3,
}
#[repr(u32)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum funnel_sync {
    FUNNEL_SYNC_IMPLICIT = 0,
    FUNNEL_SYNC_EXPLICIT = 1,
    FUNNEL_SYNC_BOTH = 2,
}
unsafe extern "C" {
    pub static FUNNEL_RATE_VARIABLE: funnel_fraction;
    pub fn funnel_init(pctx: *mut *mut funnel_ctx) -> ::std::os::raw::c_int;
    pub fn funnel_shutdown(ctx: *mut funnel_ctx);
    pub fn funnel_stream_create(
        ctx: *mut funnel_ctx,
        name: *const ::std::os::raw::c_char,
        pstream: *mut *mut funnel_stream,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_buffer_callbacks(
        stream: *mut funnel_stream,
        alloc: funnel_buffer_callback,
        free: funnel_buffer_callback,
        opaque: *mut ::std::os::raw::c_void,
    );
    pub fn funnel_stream_set_size(
        stream: *mut funnel_stream,
        width: u32,
        height: u32,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_mode(
        stream: *mut funnel_stream,
        mode: funnel_mode,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_sync(
        stream: *mut funnel_stream,
        frontend: funnel_sync,
        backend: funnel_sync,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_rate(
        stream: *mut funnel_stream,
        def: funnel_fraction,
        min: funnel_fraction,
        max: funnel_fraction,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_get_rate(
        stream: *mut funnel_stream,
        prate: *mut funnel_fraction,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_clear_formats(stream: *mut funnel_stream);
    pub fn funnel_stream_configure(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_stream_start(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_stream_stop(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_stream_destroy(stream: *mut funnel_stream);
    pub fn funnel_stream_dequeue(
        stream: *mut funnel_stream,
        pbuf: *mut *mut funnel_buffer,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_enqueue(
        stream: *mut funnel_stream,
        buf: *mut funnel_buffer,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_return(
        stream: *mut funnel_stream,
        buf: *mut funnel_buffer,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_skip_frame(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_buffer_get_size(buf: *mut funnel_buffer, pwidth: *mut u32, pheight: *mut u32);
    pub fn funnel_buffer_set_user_data(
        buf: *mut funnel_buffer,
        opaque: *mut ::std::os::raw::c_void,
    );
    pub fn funnel_buffer_get_user_data(buf: *mut funnel_buffer) -> *mut ::std::os::raw::c_void;
    pub fn funnel_buffer_has_sync(buf: *mut funnel_buffer) -> bool;
    pub fn funnel_buffer_is_efficient_for_rendering(buf: *mut funnel_buffer) -> bool;
}
