/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_ctx {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_stream {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_buffer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct funnel_fraction {
    pub num: u32,
    pub den: u32,
}
pub type funnel_buffer_callback = ::std::option::Option<
    unsafe extern "C" fn(
        opaque: *mut ::std::os::raw::c_void,
        stream: *mut funnel_stream,
        buf: *mut funnel_buffer,
    ),
>;
#[repr(u32)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum funnel_mode {
    FUNNEL_ASYNC = 0,
    FUNNEL_DOUBLE_BUFFERED = 1,
    FUNNEL_SINGLE_BUFFERED = 2,
    FUNNEL_SYNCHRONOUS = 3,
}
#[repr(u32)]
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum funnel_sync {
    FUNNEL_SYNC_IMPLICIT = 0,
    FUNNEL_SYNC_EXPLICIT = 1,
    FUNNEL_SYNC_BOTH = 2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkImage_T {
    _unused: [u8; 0],
}
pub type VkImage = *mut VkImage_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkInstance_T {
    _unused: [u8; 0],
}
pub type VkInstance = *mut VkInstance_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkPhysicalDevice_T {
    _unused: [u8; 0],
}
pub type VkPhysicalDevice = *mut VkPhysicalDevice_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkDevice_T {
    _unused: [u8; 0],
}
pub type VkDevice = *mut VkDevice_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkSemaphore_T {
    _unused: [u8; 0],
}
pub type VkSemaphore = *mut VkSemaphore_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkFence_T {
    _unused: [u8; 0],
}
pub type VkFence = *mut VkFence_T;
pub type VkFormat = ::std::os::raw::c_uint;
pub type VkFormatFeatureFlagBits = ::std::os::raw::c_uint;
pub type VkImageUsageFlagBits = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub static FUNNEL_RATE_VARIABLE: funnel_fraction;
    pub fn funnel_init(pctx: *mut *mut funnel_ctx) -> ::std::os::raw::c_int;
    pub fn funnel_shutdown(ctx: *mut funnel_ctx);
    pub fn funnel_stream_create(
        ctx: *mut funnel_ctx,
        name: *const ::std::os::raw::c_char,
        pstream: *mut *mut funnel_stream,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_buffer_callbacks(
        stream: *mut funnel_stream,
        alloc: funnel_buffer_callback,
        free: funnel_buffer_callback,
        opaque: *mut ::std::os::raw::c_void,
    );
    pub fn funnel_stream_set_size(
        stream: *mut funnel_stream,
        width: u32,
        height: u32,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_mode(
        stream: *mut funnel_stream,
        mode: funnel_mode,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_sync(
        stream: *mut funnel_stream,
        frontend: funnel_sync,
        backend: funnel_sync,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_set_rate(
        stream: *mut funnel_stream,
        def: funnel_fraction,
        min: funnel_fraction,
        max: funnel_fraction,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_get_rate(
        stream: *mut funnel_stream,
        prate: *mut funnel_fraction,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_clear_formats(stream: *mut funnel_stream);
    pub fn funnel_stream_configure(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_stream_start(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_stream_stop(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_stream_destroy(stream: *mut funnel_stream);
    pub fn funnel_stream_dequeue(
        stream: *mut funnel_stream,
        pbuf: *mut *mut funnel_buffer,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_enqueue(
        stream: *mut funnel_stream,
        buf: *mut funnel_buffer,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_return(
        stream: *mut funnel_stream,
        buf: *mut funnel_buffer,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_skip_frame(stream: *mut funnel_stream) -> ::std::os::raw::c_int;
    pub fn funnel_buffer_get_size(buf: *mut funnel_buffer, pwidth: *mut u32, pheight: *mut u32);
    pub fn funnel_buffer_set_user_data(
        buf: *mut funnel_buffer,
        opaque: *mut ::std::os::raw::c_void,
    );
    pub fn funnel_buffer_get_user_data(buf: *mut funnel_buffer) -> *mut ::std::os::raw::c_void;
    pub fn funnel_buffer_has_sync(buf: *mut funnel_buffer) -> bool;
    pub fn funnel_buffer_is_efficient_for_rendering(buf: *mut funnel_buffer) -> bool;
    pub fn funnel_stream_init_vulkan(
        stream: *mut funnel_stream,
        instance: VkInstance,
        physical_device: VkPhysicalDevice,
        device: VkDevice,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_vk_set_usage(
        stream: *mut funnel_stream,
        usage: VkImageUsageFlagBits,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_stream_vk_add_format(
        stream: *mut funnel_stream,
        format: VkFormat,
        alpha: bool,
        features: VkFormatFeatureFlagBits,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_buffer_get_vk_image(
        buf: *mut funnel_buffer,
        pimage: *mut VkImage,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_buffer_get_vk_format(
        buf: *mut funnel_buffer,
        pformat: *mut VkFormat,
        phas_alpha: *mut bool,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_buffer_get_vk_semaphores(
        buf: *mut funnel_buffer,
        pacquire: *mut VkSemaphore,
        prelease: *mut VkSemaphore,
    ) -> ::std::os::raw::c_int;
    pub fn funnel_buffer_get_vk_fence(
        buf: *mut funnel_buffer,
        pfence: *mut VkFence,
    ) -> ::std::os::raw::c_int;
}
